services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
      - frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: "${DOMAIN_NAME}"
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - frontend

networks:
  backend:
  frontend:


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/maxvalk/Desktop/Codam/inception/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/maxvalk/Desktop/Codam/inception/data/wordpress
      o: bind
