services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-php
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - docker_network

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - docker_network
    volumes:
      - wordpress_data:/var/www/html

networks:
  docker_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/maxvalk/Desktop/Codam/inception/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/maxvalk/Desktop/Codam/inception/data/wordpress
      o: bind
