services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - /home/mvalk/data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h localhost -u root -p\"$${MYSQL_ROOT_PASSWORD}\" --silent" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /home/mvalk/data/wordpress:/var/www/html
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - /home/mvalk/data/wordpress:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
